# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Checks that are intended to publish PRs test results from JUnit.

name: Java PR Report
on:
  workflow_run:
    workflows:
      - Java PR
      - Spanner PR
      - Release
    types: [ completed ]

permissions:
  checks: write # Need to write reports

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Download Test Report
      uses: dawidd6/action-download-artifact@5c98f0b039f36ef966fdb7dfa9779262785ecb05 # v14
      with:
        name: surefire-.*test-results
        name_is_regexp: true
        workflow: ${{ github.event.workflow.id }}
        run_id: ${{ github.event.workflow_run.id }}
        if_no_artifact_found: warn
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@74626db7353a25a20a72816467ebf035f674c5f8 # v6.2.0
      with:
        commit: ${{github.event.workflow_run.head_sha}}
        report_paths: |
          **/surefire-reports/TEST-*.xml
          **/surefire-reports/*.html
          **/surefire-reports/html/**